### ISSUE TITLE
`scala.MatchError: List(A suitable version of cmake was not found (required v3.24.0). Downloading portable cmake v3.24.0...)`

### ISSUE THREAD

**Issue by armanbilge** [indoorvivants/sbt-vcpkg#36]
```
[error] scala.MatchError: List(A suitable version of cmake was not found (required v3.24.0). Downloading portable cmake v3.24.0...) (of class scala.collection.immutable.$colon$colon)
[error]         at com.indoorvivants.vcpkg.Vcpkg$Dependencies$.$anonfun$parse$1(Vcpkg.scala:148)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at com.indoorvivants.vcpkg.Vcpkg$Dependencies$.parse(Vcpkg.scala:147)
[error]         at com.indoorvivants.vcpkg.Vcpkg.dependencyInfo(Vcpkg.scala:79)
[error]         at com.indoorvivants.vcpkg.VcpkgPluginImpl.$anonfun$vcpkgInstallImpl$2(VcpkgPluginImpl.scala:41)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error]         at scala.collection.immutable.Set$Set1.foreach(Set.scala:141)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error]         at com.indoorvivants.vcpkg.VcpkgPluginImpl.vcpkgInstallImpl(VcpkgPluginImpl.scala:40)
[error]         at com.indoorvivants.vcpkg.VcpkgPluginImpl.vcpkgInstallImpl$(VcpkgPluginImpl.scala:32)
[error]         at com.indoorvivants.vcpkg.sbt.VcpkgPlugin$.vcpkgInstallImpl(VcpkgPlugin.scala:16)
[error]         at com.indoorvivants.vcpkg.sbt.VcpkgPlugin$.$anonfun$projectSettings$15(VcpkgPlugin.scala:67)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:833)
[error] (ioNative / vcpkgInstall) scala.MatchError: List(A suitable version of cmake was not found (required v3.24.0). Down
```

**Comment by keynmol** [comment]
Note to future self - figure out what vcpkg actually does at this point, because either it downloads the new cmake _blazingly fast_, or it downloads it in the background, while my main process fails.

Because usually running the command again fixes it. Is this what you saw @armanbilge? or did it not recover?

**Comment by armanbilge** [comment]
Sorry, I can't remember 😕 it's quite possible I tried it more than once, but in the end I ended up updating via brew.

I just opened a clean workspace but I cannot reproduce. That suggests to me it was transient /shrug

**Comment by armanbilge** [comment]
Aha, I was able to reproduce. And you were right: first time fails, but running the command a second time succeeds.
